controllers:
    resource: ../src/Controller/
    type: attribute

register:
    path: /register
    controller: App\Controller\ApiController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\ApiController::api

check_path:
    path: /authentication_token
    methods: [ POST ]

api_login_check:
    path: /api/login_check